### ISSUE TITLE
Firefox copy/paste

### ISSUE THREAD

**Issue by allox** [andyvr/picEdit#10]
Copy/paste an image from FF to picedit (in another tab in FF) doesnt work (on ubuntu). 
At first I expected it to be some FF bug (because it is ok in Chromium), but it turns out that it is possible, according to this http://jsfiddle.net/KJW4E/361/

**Comment by andyvr** [comment]
Copy/paste from FF tab to FF tab indeed works, but only to the point where you want to display the image, unless the image is not allowed by CORS you won't be able to edit it.
In other words:
This image can't be copy/pasted from FF to FF because it's CORS policy is restrictive:
http://www.jpl.nasa.gov/spaceimages/images/mediumsize/PIA17011_ip.jpg
This image can be copy/pasted from FF to FF, again because the CORS policy allows for it:
http://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50.jpg
You can try both images in the picEdit demo to see what I mean.
Again the first image is possible to display, but won't be possible to edit, but second image can be edited.
There's no point in displaying an image that cant be edited in the picEdit, that's why not all images can be copy/pasted.

**Comment by allox** [comment]
No, both images can not be copy/pasted.  
(FF 35, Ubuntu 14.04. But I have heard similar issues from windows FF users. )

**Comment by andyvr** [comment]
Hard-refresh the demo page/clear the cache. The demo files have been updated.

**Comment by andyvr** [comment]
I think I'll add user notifications when the copy/paste is not successful.
