### ISSUE TITLE
picEdit submits only the original image

### ISSUE THREAD

**Issue by renebrain** [andyvr/picEdit#25]
Hi,

i found out about this tool today and added in one of my projects. My problem is, that although i can modify the picture, he always submits the original image. He is not taking any of the changes. Here ist my code:

 		 $("#image").picEdit({
		         redirectUrl: baseURL + "/userinfo",
			 defaultImage: false
		 });
```xml
<form method="POST" enctype="multipart/form-data" action="user/addimage">
<input id="image" accept="image/*" type="file" name="userimage">
<button type="submit" class="btn btn-primary btn-lg"><spring:message code="common.submit.save"/></button>
</form>
```
What am i doing wrong? Is it not working with multipart/form-data or something like that?

**Comment by simonpapworth6742** [comment]
There is a second image which has your changes, it is submitted at the same time as the first. I ended up changing the script to empty the first image myself.

**Comment by KokoRyuKai** [comment]
@simonpapworth6742  You've mentioned at edit to blank the first image in order to get the editted image, can you post a sample or open a fork or something.

**Comment by desnudopenguino** [comment]
@KokoRyuKai, if you haven't figured it out yet, what you can do is set the file name in the html form to an array e.g. name="image[]". Then you can remove the index 0 attributes or use the index 1 attributes. It saves it as image( 'name' => array('original_filename','altered_filename'), 'tmp_name' => array('original_tmp_name','altered_tmp_name') ...

**Comment by sonixtwo** [comment]
@desnudopenguino , I get the concept, but don't understand your code.  Can you please elaborate?

Thanks!

**Comment by desnudopenguino** [comment]
This is all going to be in PHP on the server side, sorry if that won't work for you, it's what I've been using most of the time recently, so I can give a complete answer in it only.


Step one, making the server able to accept the altered image:
use `<input type="file" name="image[]" />` instead of `<input type="file" name="image" />` in your html. Otherwise the original image is all the server sees. It sets it up to make $_POST['image'] an array.


Step two, now that you can parse the data, you need to make sure you are pulling the right image into your server code.


The data sent to the server will look like this:
```
[_FILES] => Array
        (
            [image] => Array
                (
                    [name] => Array
                        (
                            [0] => filename.jpg
                            [1] => filename.jpg 
                    [type] => Array
                      (
                           [0] => ...
                           [1] => ...
                    [tmp_name] => Array
                      (
                          [0] => /tmp/aoeu897u
                          [1] => /tmp/uau4pyao4

                    [error] => Array
                        (
                             [0] => 0
                             [1] => 0
                            ...
                    [size] => Array ...
                )
        )
```

So you have to get the [1] thing in each of the sub-items in the image array. If you already have some elaborate code written and don't care about the original image you can write a quick foreach that jumps through the list of fields like this...

```
foreach($_FILES['image'] as $attribute_name => $attribute_value) {
    $_FILES['image'][$attribute_name] = $attribute_value[1];
}

```

That should parse everything back out to the way it would be without dealing with multiple images. You can do that or access the [1]st things it the arrays. Whichever is easier for you. I hope this helps.

**Comment by Pandahisham** [comment]
:+1: @desnudopenguino

**Comment by mmr99869** [comment]
Hi everyone,

You can also **send always the edited image through AJAX** by using the [Blob](https://developer.mozilla.org/es/docs/Web/API/Blob) object. For example:

    var thereIsBlob = false;
    var uploaded_photo;
    $("#myInputFileElement").picEdit({
        imageUpdated: function(img) {
            if ((typeof img.file === "undefined") && (typeof img.src !== "undefined")) {
                uploaded_photo = dataURItoBlob(img.src);
                thereIsBlob = true;
            }
            else {
                uploaded_photo = img.file;
                thereIsBlob = false;
            }
        }
    });
    // (...)
    var data = new FormData();
    if ((typeof uploaded_photo !== "undefined")) {
        if (thereIsBlob) data.append("photo", uploaded_photo, "photo.png");
        else data.append("photo", uploaded_photo);
    }
    // AJAX call code with the FormData and so on

The **dataURItoBlob** function converts the Data URI obtained from img.src to a Blob object that can be sent like a file to a PHP script (or another kind of file) through AJAX. You can find how to implement that JS function on the Internet.

I hope this helps!

**Comment by andyvr** [comment]
I want to bring some kind of clarification to this thread.
Due to limitations in HTML5 Form API its impossible to actually update the file-upload in the original form. Instead, what picEdit does is duplicates your original html form in javascript, substitutes the file-upload on the fly and sends the whole form thru Ajax. Your original form is not being sent.
However, if your original form has a custom "submit" event handler attached, it can cause your original form submitting to the server along with the Ajax POST request from picEdit. You'll see it as the "double submission", when the edited image is being sent along with the original one.
Depending on your code you might want to tweak your custom js code to make it work with picEdit.

**Comment by andyvr** [comment]
Meanwhile, I'm working on the alternative way to submit the image data to simplify the upload process and overcome the above issues.
