### ISSUE TITLE
jquery pigEdit cause fail to RedirectToAction in MVC

### ISSUE THREAD

**Issue by phancongphuoc** [andyvr/picEdit#7]
I try pigEdit in my website, everything is ok except after post to ActionResult, it can not be RedirecToAction to other ActionResult
When i change the pigEdit to commont file, it is ok

Looking at the .js file, I saw that there are many preventDefault, I think that is the cause of this issue, but I have no idea how to fix.

Thanks

**Comment by andyvr** [comment]
Due to the nature of the "HTML form API" you cannot update the file input directly with the modified image. Instead it's being submitted by the XHR post request.
I'm currently working on alternative ways to handle this situation. However, currently, the plugin submits the form on it's own and prevents all other submit actions.
If you want to redirect your user to a thank you page, just set the "redirectUrl" parameter.
